### ISSUE TITLE
Login 

### ISSUE THREAD

**Issue by fatimaTalavera** [EmilioCenturion/uni-sistemas-2015#11]
Se debe crear una interfaz para el login, no se precisa (por el momento), que funcione con perfiles por usuario. Se utilizara la gema devise.

La ventana principal te permitira la opcion de login, no asi el crear nuevos usuarios, ya que eso lo definira el administrador del sistema asignandole permisos para la misma. En la ventana principal solo deben figurar los campos usurio y contraseña, no el navbar ni ninguna otra caracteristica interna del sistema.

Una vez ingresado en la parte superior derecha aparecera el nombre del usuario y un boton que permita cerrar la sesión.

**Comment by ergo-program** [comment]
Pendiente:
Falta la interfaz para el inicio de un administrador por el momento permite crear usuarios varios.
