### ISSUE TITLE
Validaciones de tarjetas y cupones

### ISSUE THREAD

**Issue by fatimaTalavera** [EmilioCenturion/uni-sistemas-2015#22]
Validaciones:
- el numero de tarjeta es unico, no es negativo
- Monto decimal, no debe permitir negativos.
- el nro_fisico es unico

Definir otros si fueren necesarios.

**Comment by fatimaTalavera** [comment]
Validaciones:
- el numero de tarjeta es unico, no es negativo
- Monto decimal, no debe permitir negativos.
- nro_fisico varchar ya que en el cupon se ingresan codigos que varian por banco para evitar duplicaciones, ej: 3336-A-0056
- el nro_fisico es unico

Definir otros si fueren necesarios.

**Comment by EmilioCenturion** [comment]
Las validaciones de tarjetas ya estan. Las validaciones faltantes son de los cupones.
