### ISSUE TITLE
Validaciones de chequeras y cheques emitidos

### ISSUE THREAD

**Issue by fatimaTalavera** [EmilioCenturion/uni-sistemas-2015#23]
Validaciones:
- el primer numero de la chequera no debe ser superior al ultimo numero
- Monto decimal, no debe permitir negativos.
- nro_fisico varchar ya que en el cheque se ingresan codigos que varian por banco para evitar duplicaciones, ej: 3336-A-0056
- el nro_fisico es unico

Definir otros si fueren necesarios.

**Comment by EmilioCenturion** [comment]
faltan las validaciones de cheques emitidos
