### ISSUE TITLE
ABM cajas 

### ISSUE THREAD

**Issue by EmilioCenturion** [EmilioCenturion/uni-sistemas-2015#31]
Se debe realizar los ABM correspondientes a cajas. 
Realizar el abm correspondiente a cajas, siguiendo las especificaciones del modelo de datos y también respetando el patrón de diseño del proyecto.

La caja debe estar cerrada, una vez abierta debe permitir crear nuevos movimientos de caja, lo cuales no son editables. Al cerrar la caja debe generar un deposito bancario de todos los montos ingresados tanto cheque como efectivo, esto genera un egreso automático en la caja.
Una vez cerrada la caja no se permite realizar movivientos en la misma

**Comment by fatimaTalavera** [comment]
ABM cajas realizado, el cual muestra las cajas de la empresa y permite dar apertura a las habilitadas
Falta:
-Apertura
-Movimientos de caja

**Comment by fatimaTalavera** [comment]
Falta
- Botón para cerrar caja

**Comment by fatimaTalavera** [comment]
Botón para cierre de caja terminado.
Mejore las vistas para apertura y cierre de caja, mostrando la lista de aperturas, habilitando o no los botones y solapas.
