### ISSUE TITLE
ABM para movimientos de cajas

### ISSUE THREAD

**Issue by EmilioCenturion** [EmilioCenturion/uni-sistemas-2015#33]
Realizar el abm correspondiente a los movimientos entre cajas, siguiendo las especificaciones del modelo de datos y también respetando el patrón de diseño del proyecto.

Una vez abierta debe permitir crear nuevos movimientos de caja, lo cuales no son editables, si surge un error se debe hacer un contra-movimiento. Al cerrar la caja debe generar un deposito bancario de todos los montos ingresados tanto cheque como efectivo, esto genera un egreso automático en la caja.
Una vez cerrada la caja no se permite realizar movivientos en la misma

**Comment by fatimaTalavera** [comment]
Falta 
- validaciones
- manejar valores negativos 
  ambos pertenecientes a tareas de validaciones

Obs: solo permite el alta de movimientos, ya que, si se tuvo un error se debe hacer un contra movimiento y no una modificación
