### ISSUE TITLE
ABM movimiento de bancos

### ISSUE THREAD

**Issue by fatimaTalavera** [EmilioCenturion/uni-sistemas-2015#37]
los movimientos de banco indican ingresos o egresos de las cuentas de banco, las mismas pueden ser por depositos, transacciones, emisión de cheques y/o cupones.

El sistema debe prever que se realicen “Movimientos varios de bancos” que podrán ser de ingresos o egresos, por ejemplo un egreso podrá ser “Gastos bancarios” o “intereses por cheque rechazado”.

**Comment by ergo-program** [comment]
Falta Agregar Trigger para manejo de saldo negativo.
