### ISSUE TITLE
Validaciones ABM movimientos caja

### ISSUE THREAD

**Issue by fatimaTalavera** [EmilioCenturion/uni-sistemas-2015#40]
Validaciones:
- tipo de movimiento puede ser ingreso o egreso
- motivo movimiento no puede ser null
- agregar un campo de "descripcion" (puede ser nulo) por si el motivo es generico, por ej: 
   Motivo: pago a proveedor
   Descripción: factura Nº xxxx, por compra de extintores ......

Definir otros si fueren necesarios.

**Comment by EmilioCenturion** [comment]
falta la verificación en la bases de datos si es única y la comparación entre el monto efectivo y detalles para validar cuando puede o no ser cero
