### ISSUE TITLE
Validaciones ABM movimientos banco

### ISSUE THREAD

**Issue by fatimaTalavera** [EmilioCenturion/uni-sistemas-2015#42]
Validaciones:
- el tipo debe ser ingreso o egreso
- motivo_id no puede ser nulo
- considerar la incluir un campo "descripción" a modo de ampliar el motivo, que puede ser nulo

Definir otros si fueren necesarios.

**Comment by EmilioCenturion** [comment]
agregue validación que no te permite hacer un egreso de monto mayor al saldo de la cuenta
