### ISSUE TITLE
Validaciones de cheques recibidos

### ISSUE THREAD

**Issue by fatimaTalavera** [EmilioCenturion/uni-sistemas-2015#44]
Validaciones:
- Monto decimal, no debe permitir negativos.
- nro_fisico varchar ya que en el cheque se ingresan codigos que varian por banco para evitar duplicaciones, ej: 3336-A-0056
- el nro_fisico es unico

Definir otros si fueren necesarios.

**Comment by EmilioCenturion** [comment]
falta la verificacion en base de datos si el nro es unico
